### ISSUE TITLE
log.Fatal hides problems

### ISSUE THREAD

**Issue by mlh758** [zhiminwen/magetool#1]
Using log.Fatal instead of returning an error means the caller has to call mage with the verbose flag to see why something is dying. It would be nicer to let the consumer of this library handle those errors as they see fit.

**Comment by zhiminwen** [comment]
Ok. Fixed by removing the Fatal call. But some client code might be broken...

**Comment by mlh758** [comment]
Thank you. I think that will make using this library a little more
straightforward. I appreciate you taking the time to make it.
